use_frameworks!

platform :ios, '8.0'

target 'hahaslsls_Example' do
  pod 'hahaslsls', :path => '../'

  target 'hahaslsls_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
